### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sirjessthebrave**
Using Outlaw instead of Refugee

Note: the email address github.outlaws@upend.org will have to be created

### CODE REVIEW

**Comment by themusicgod1** [comment]
Outlaw implies outside of the rule of law in some sense.  Which maybe it might come to, but there's plenty pro-capitalist, pro-rule of law developer that could be appealed to, a lot more than refugees probably by not using the world 'outlaw' here.

**Comment by sirjessthebrave** [comment]
So we can deconstruct the implications of the word outlaw but not refugee? Honestly just pick another one.. rebel, dissident, pirate, defector, renegade, castaway

**Comment by themusicgod1** [comment]
I never said we couldn't deconstruct the implications of the word refugee.  I would say the implications are the correct implications.  castaway might work

**Comment by sirjessthebrave** [comment]
Well NM looks like he found a better word: 'Evacuation'. Closing this PR

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas

**Pull request closed without merging**
