### PR TITLE
Fixed Typo in the readme.md file

### PR DESCRIPTION
**Pull request by NeumimTo**
Fixed Typo in the readme.md file

### CODE REVIEW

**Comment by changyuheng** [comment]
Why is it a typo?

**Comment by NeumimTo** [comment]
It is.

**Comment by sci4me** [comment]
No, it's supposed to be "your"; learn grammar. Jesus.

**Comment by r00ster91** [comment]
Thats not a typo.

**Comment by NeumimTo** [comment]
It is

**Comment by AkgunFatih** [comment]
wtf bro are you high or something ?

**Comment by sci4me** [comment]
He's probably another troll.

**Comment by amwmedia** [comment]
Can we please change the wording from "you" and "your" to "us" and "our" to be more inclusive to the wider community?

**Comment by vassudanagunta** [comment]
@amwmedia yes! can you do a pull request?

**Comment by amwmedia** [comment]
my comment was total sarcasm (in case anyone wasn't sure), but it actually WOULD read nicely with that verbiage change 😂

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas

**Pull request closed without merging**
