### PR TITLE
New list of app/services destroyed by Microsoft acquisition

### PR DESCRIPTION
**Pull request by savo92**

### CODE REVIEW

**Comment by darkpixel** [comment]
I miss Sunrise calendar.  It was such a handy tool...

**Comment by savo92** [comment]
I really miss it too. It was the only calendar app in the history that didn't make me crazy

**Comment by SFoskitt** [comment]
Skype
Wunderlist

**Comment by vassudanagunta** [comment]
I hear you. I have strong feelings about Microsoft too, having lived through the 90s. But this isn't about Microsoft. 

[As I tweeted](https://twitter.com/UpEnd_org/status/1003475525619404801), and probably should put in the README:
> It's not about Microsoft. It's about the independence of the de-facto home of the #opensource community. It shouldn't be owned by any company with ANY agenda OTHER THAN servicing this community.

Or if you look at the photo on the README. The problem in *this* picture isn't Microsoft, it's the guy, GitHub.  [As one person on Twitter put it](https://twitter.com/CWDillon/status/1003614146989043717):

> Yah, it's like GitHub just asked for a 3some with Microsoft and expects it not to affect our relationship. 
It's one or the other and you've already declared your preference.

So I'm not going to merge this. But keep the info handy. As we spin up UpEnd.org and talk about what's wrong with so few controlling so much of the internet, it may go there.

**Comment by darkpixel** [comment]
I expect companies to have an agenda.  You aren't a business if you don't bring in a profit and keep the shareholders/investors happy.  That should be the primary agenda.  It's tightly coupled with "provide a valuable service" and "convince people to pay for the service".

You haven't clearly defined what Microsoft's agenda is or how it conflicts with some nebulous 'open source' agenda.

I'm sure I speak for a lot of people.  It *is* simply about Microsoft.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas

**Pull request closed without merging**
