### PR TITLE
 replace machist meme with a feminist meme

### PR DESCRIPTION
**Pull request by albjeremias**
yeah.. that.

### CODE REVIEW

**Comment by vassudanagunta** [comment]
1. Nice try, buddy, trying to hijack the image link. "society.oftrolls"  Yes. Indeed.
2. "feminist". BS. Most of my friends are women and feminist, and they'll call bullshit on your simplistic patriarchal idea of "feminist".

**Comment by vassudanagunta** [comment]
You were hijacking the link. In a pull request about replacing an image. Not cool. 

This is a serious project. Can you contribute something that advances it? We need the ethics without the trolling.

**Comment by vassudanagunta** [comment]
@albjeremias on the subject of sexism: [it turns out I was blind](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/pull/58#issuecomment-394811185) to the insensitivity if not sexism in that meme. I'm glad @mtwentyman called it out. I apologize for not seeing the truth in that part of your comment. 

But your pull request is still a hijack, and i'm not sure your replacement image helps or hurts fight sexism and male insensitive to women's issues. I also don't want to make this effort to be advertising for GitLab. Not everyone agrees it is the right alternative. As part of this project, we'll discuss that and come up with some kind of recommendation.

**Comment by albjeremias** [comment]
ok, i apologize for taking over the link.. but it was the source... :o you had the source of the image in there before... i didn't meant it...

**Comment by vassudanagunta** [comment]
ok no worries. anyway, we're not doing any meme any more.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas

**Pull request closed without merging**
