### PR TITLE
Create GITLAB_MIGRATION_GUIDE.MD

### PR DESCRIPTION
**Pull request by XakepSDK**
Migration guide to gitlab

### CODE REVIEW

**Comment by vassudanagunta** [comment]
This is great work. But it needs to be published somewhere else (probably on GitLab given what you're implicitly recommending).

The reason I can't post it here is because:
1. See Issue 114
2. It's recommending GitLab, and not everyone agrees that's what should be recommended. 

What I can do is link to it, with the text, "If you choose to migrate to GitLab, this guide will make it easier". 

But question, what does this provide on top of what I'm sure GitLab itself is already providing evacuees?

**Comment by Serphentas** [comment]
Given that we discuss the alternatives [here](https://github.com/bderiso/Microsoft-Github-acquisition/issues), it would probably be a good idea to compile various guides over there for those who wish to continue with GitLab until the community decides what to use next.

What do you think ?

**Comment by vassudanagunta** [comment]
reminder this forum is shutting down in 5 hours 20 minutes.

**Comment by Serphentas** [comment]
I've migrated the current guide [here](https://github.com/bderiso/Microsoft-Github-acquisition/blob/master/migration_guide_gitlab.md).

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas

**Pull request closed without merging**
